const { run } = require('react-snap')

run({
  source: 'dist',
  publicPath: '/era-react-website',
  include: [
    '/',
    '/products',
    '/products/gota',
    '/products/mbajtese',
    '/products/akullore',
    '/products/kupa-supe',
    '/products/leter-tavoline',
    '/products/kuti-hamburgeri',
    '/products/kuti-sllajder',
    '/products/kuti-fast-food',
    '/products/kuti-6pika',
    '/products/kuti-hapur',
    '/products/kuti-krepa',
    '/products/kuti-sallata',
    '/products/kuti-makaronash',
    '/products/caj-heksagonal',
    '/products/caj-gable-top',
    '/products/kuti-pomfrit',
    '/products/mbajtese-kafe',
    '/products/kuti-sanduic',
    '/products/kuti-dhurate',
    '/machines',
    '/about',
    '/contact',
  ],
  puppeteerExecutablePath: process.env.PUPPETEER_EXECUTABLE_PATH ||
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  puppeteerArgs: ['--no-sandbox', '--disable-setuid-sandbox'],
  skipThirdPartyRequests: true,
  viewport: { width: 1440, height: 900 },
  crawl: false,
  saveAs: 'html',
})
